### PR TITLE
WAMP: implement ticket auth

### PR DESCRIPTION
**Pull request by om26er**
This _works_ but needs an API review from @oberstet, I still need to extend the Session.join() to accept sessionID as a parameter as well.

Also need to define the API through which the user code returns a ChallengeResponse, with the current proposed version, the developer must add a `onChallengeListener` to the Session class with method `setOnChallengeListener`.

### CODE REVIEW

**Comment by oberstet** [comment]
Cool, this already looks almost complete! Regarding how user code would handle a challenge: this should be added by the app developer on the authmethod: https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/auth/AnonymousAuth.java#L29

**Comment by om26er** [comment]
> Cool, this already looks almost complete! Regarding how user code would handle a challenge: this should be added by the app developer on the authmethod: https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/auth/AnonymousAuth.java#L29

Pushed an update through which `TicketAuth` object can be passed to the Client constructor (List<IAuthenticator>). Kindly take a relook.

**Comment by om26er** [comment]
So once we land this, we can quickly get WAMP-CRA done and then later cryptosign.

**Comment by oberstet** [comment]
perfect! I think (again): ABJ has now a state of the art design on this part of a WAMP client library. clean, simple user API. straight forward implementation. cool=)

**Pull request merged**
