### PR TITLE
Pass WebSocketOptions to NettyTransport

### PR DESCRIPTION
**Pull request by om26er**
Fixes one part of https://github.com/crossbario/autobahn-java/issues/243 -- still need to add more serializers.

### CODE REVIEW

**Comment by om26er** [comment]
oh, I know the reason for the failure. We do not ship `io.crossbar.autobahn.websocket` package with netty based WAMP implementation, would need to change that.

**Comment by om26er** [comment]
Actually if we include the websocket package we need Android development environment for the library to actually build. So I am clueless on what we shall do, maybe Make a copy of WebSocket options in `io.crossbar.autobahn.websocket` ?

**Comment by oberstet** [comment]
Yeah, probably just copy over!

**Comment by om26er** [comment]
Ok, CI is happy now.

The copied over file is big with many features we don't need. How about I remove everything except `mMaxFramePayloadSize` options and we can add things further as required ?

**Comment by om26er** [comment]
> How about I remove everything except mMaxFramePayloadSize options and we can add things further as required ?

Well, I answered myself :) I think it makes sense to keep the new file minimal and extend as the need arises.

**Comment by om26er** [comment]
Right now I put the new file under `io.crossbar.autobahn.wamp.types` we may move it around later, maybe to the root `wamp` package.

**Pull request merged**
