### PR TITLE
add script to support older versions of android

### PR DESCRIPTION
**Pull request by om26er**
Run this script and then compile the project from Android Studio to have WAMP working on Android 4.0.3+

### CODE REVIEW

**Comment by oberstet** [comment]
woah, if that works, cool;)

**Comment by om26er** [comment]
@oberstet how about a release based on streamsupport `autobahn-android-legacy` (or a better name) ? (Apart from `autobahn-java` and `autobahn-android`)

**Comment by filipefreitas82** [comment]
I can't get this work, with devices with sdk lower than 26, maybe because of the way I'm building my app.

I'm using Intellijj IDE. Here is my build.gradle:
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "pt.doutorfinancas.mobile.easycall"
        minSdkVersion 18
        targetSdkVersion 26
        versionCode 2
        versionName "1.1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:+'
    compile 'com.google.code.gson:gson:2.8.2'
    implementation 'io.crossbar.autobahn:autobahn-android:17.10.5'
    testCompile 'junit:junit:4.12'
}
```

Do I have to download all of the sourcecode and then run the script?
thanks

**Comment by om26er** [comment]
> Do I have to download all of the sourcecode and then run the script?

The fact that its not documented is because we are not currently supporting old androids.

You don't have to change anything manually. Only execute the `enable_old_androids.sh` script on the root of the source code and then recompile the project with Android studio. I plan to publish a -legacy build in future as well.

**Comment by filipefreitas82** [comment]
I'm getting this error:

```
sed: 1: "autobahn/build.gradle": command a expects \ followed by text
```

**Comment by filipefreitas82** [comment]
The error is because I'm on a mac and the sed command is different.

**Comment by filipefreitas82** [comment]
Here is the updated script for macos in case anyone is interested:

```
#!/bin/sh

set -e

# Uncomment streamsupport gradle library
sed -i '' "s|//api 'net.sourceforge.streamsupport:streamsupport-cfuture:|api 'net.sourceforge.streamsupport:streamsupport-cfuture:|g" autobahn/build.gradle

# Change SDK support to Android 4.0.3
sed -i '' 's/minSdkVersion.*/minSdkVersion 15/g' autobahn/build.gradle
sed -i '' 's/minSdkVersion.*/minSdkVersion 15/g' demo-gallery/build.gradle

# Replace imports to streamsupport.
find . -type f -name '*.java' -exec sed -i '' 's/import static java.util.concurrent.CompletableFuture.runAsync;/import static java8.util.concurrent.CompletableFuture.runAsync;/g' {} +
find . -type f -name '*.java' -exec sed -i '' 's/import java.util.concurrent.CompletableFuture;/import java8.util.concurrent.CompletableFuture;/g' {} +
find . -type f -name '*.java' -exec sed -i '' 's/import java.util.concurrent.CompletionException;/import java8.util.concurrent.CompletionException;/g' {} +
find . -type f -name '*.java' -exec sed -i '' 's/import java.util.concurrent.ForkJoinPool;/import java8.util.concurrent.ForkJoinPool;/g' {} +
find . -type f -name '*.java' -exec sed -i '' 's/import java.util.function.BiConsumer;/import java8.util.function.BiConsumer;/g' {} +
find . -type f -name '*.java' -exec sed -i '' 's/import java.util.function.BiFunction;/import java8.util.function.BiFunction;/g' {} +
find . -type f -name '*.java' -exec sed -i '' 's/import java.util.function.Consumer;/import java8.util.function.Consumer;/g' {} +
find . -type f -name '*.java' -exec sed -i '' 's/import java.util.function.Function;/import java8.util.function.Function;/g' {} +
find . -type f -name '*.java' -exec sed -i '' 's/import java.util.function.Supplier;/import java8.util.function.Supplier;/g' {} +
```

**Pull request merged**
