### PR TITLE
Implement EIP712 Signing

### PR DESCRIPTION
**Pull request by om26er**
* Brings in web3j implementation of EIP712 in our code
* The upstream web3 implementation had a few crashes, fixes those as well
* The XBR Seller is actually able to sell stuff now
* Forked SealedBox implementation as upstream implementation had issues

Note: The XBR buyer is still not implemented but that should be straightforward enough. In a second batch of updates, I need to clean up the code as well.

### CODE REVIEW

**Comment by oberstet** [comment]
looks good! seems like `org.web3j` does indeed have the bits we need .. and also, reading code is straight forward, as it mirrors closely the ABPy and ABJS pendants -- nice=)

**Comment by om26er** [comment]
This took much longer than I expected, I basically got stuck into the EIP712 implementation of webj3 for a few days. Once signing was figured out, I was hit with an unexpected bug of SealedBox, which took yet another day to track down ;-)

**Comment by oberstet** [comment]
;) great work! yeah, EIP712 was also what practically sucked up a lot of time in the other ABs ..

**Comment by oberstet** [comment]
^ ehh, I should actually click those buttons to make a merge happen .. ;)

**Comment by oberstet** [comment]
also, rereading the PR: the code and _implementation_ looks nice and fits naturally into the rest of ABJ .. nice=)

**Pull request merged**
