### PR TITLE
Getting started (first pass)

### PR DESCRIPTION
**Pull request by om26er**
Sample here: https://github.com/om26er/autobahn-java/tree/getting-started

### CODE REVIEW

**Comment by oberstet** [comment]
yeah, adding the basic-4-actions README example is a good idea! a suggestion: could we split the 4 actions into 4 onJoin handlers? this then demonstrates the observer pattern as well, and I also expect the code to become easier to grasp visually, as the code blocks get short.

> on a sidenote: actually, having a new working ABJ/Netty example that closely replicates https://github.com/crossbario/crossbar-fabric-center-oem/blob/master/test/app1/client.py would be cool! because we have that in multiple ABs, and these components can be started in multiple instances per class and in total (note the use of *shared registrations* - which is a feature I will need on the workshop to demonstrate the microservice scaleout thingy ..).

**Comment by om26er** [comment]
@oberstet I have split the example to 4 individual examples. Will add examples for the observer pattern.

Regarding new example, is it, more or less https://github.com/crossbario/autobahn-python#wamp-application-component what you want ? In that case I already have that, just need to push it to this repo.

**Comment by oberstet** [comment]
ideally, we have 4 codes blocks with code for the 4 actions (nicely formatted, without horiz. scrollbox), and after that a 5th section with the boilerplate code of actually having a Java program with a Transport and etc etc.

The example I linked has specific signatures for the event handler and such, and exposes "expected information" - can't find it now, but somewhere I created this in basically all other ABs so you can do cross-language interop testing - which is a highly useful thing in its own which we totally should do.

**Comment by om26er** [comment]
I tried to fix the indentation of the 4 WAMP actions.

Also added a fifth block that demonstrate it all. Will now work on the new example.

**Comment by om26er** [comment]
Please check the updated version here: https://github.com/om26er/autobahn-java/tree/getting-started

**Comment by oberstet** [comment]
@om26er this section looks good now! The section should be named "Show me some code", and we should have one more (new) section "Getting started", that actually describes how to run the demos (that is, one Docker container with CB, one with the Py component, and then ABJ). Lastly, we can remove the "docs" folder. With the former, I'd merge this one, as it then has all the very basic information for a user to get introduced to ABJ and actually get started trying something,

**Comment by om26er** [comment]
@oberstet section is now named "Show me some code" also deleted the docs directory. The last bit is "getting started" section. Will get that now.

**Comment by om26er** [comment]
@oberstet Kindly take a look whenever you can and suggest any changes

**Pull request merged**
