### PR TITLE
Implement custom SocketFactory setter

### PR DESCRIPTION
**Pull request by hedhyw**
It allows to set custom  SocketFactory

### CODE REVIEW

**Comment by oberstet** [comment]
SocketFactories are a transport detail that should not be exposed via IWebSocket - which is for WebSocket

**Comment by hedhyw** [comment]
What is the best way to control the transport detail?

**Comment by hedhyw** [comment]
I need to have my custom `Socket` from `SocketFactory.createSocket()`.

**Comment by oberstet** [comment]
Are we talking about Android or Netty as run-time environment? I guess best would be if you could describe your need and goals in an issue. Then we have a proper place to comment, and come up with a solution ..

**Pull request closed without merging**
