### PR TITLE
Update Session.java. Fix TicketAuth null authextra

### PR DESCRIPTION
**Pull request by andzejsw**
Fix null authextra data in TicketAuth scenario.

### CODE REVIEW

**Comment by andzejsw** [comment]
Fix for issue: https://github.com/crossbario/autobahn-java/issues/561

**Comment by andzejsw** [comment]
> might make sense to do a similar treatment for cra auth as well

It already has correct implementation of authextra.

Ekrānuzņēmums 2024-11-26 184749

**Review by om26er — APPROVED** [review]
LGTM

**Comment by oberstet** [comment]
thanks for contributing @andzejsw , and thanks for reviewing @om26er !

**Pull request merged**
