### PR TITLE
Always deserialize numbers to long

### LINKED ISSUE #363: Parsing bug in Event  Long/Integer
There is a parsing bug in the io.crossbar.autobahn.wamp.messages.Event parse method.

```java
    public static Event parse(List<Object> wmsg) {
        MessageUtil.validateMessage(wmsg, MESSAGE_TYPE, "EVENT", 3, 6);
        long subscription = (long) wmsg.get(1);
        long publication = (long) wmsg.get(2);
```
The code expects the subscription id to be a long but this can be an Integer.
The reason for that is the jackson parser deserializes numbers into Integers if the value fits into the range of an Integer.

In my example the Broker sends back a subscription id of 2. According to the specification this is a valid value.

All these identifiers can be Integers and Longs (if the number does not fit into an Integer)
>    1.  Sessions (_global scope_)
>    2.  Publications (_global scope_)
>    3.  Subscriptions (_router scope_)
>    4.  Registrations (_router scope_)
>    5.  Requests (_session scope_)
>    These are identified in WAMP using IDs that are integers between
>    (inclusive) *0* and *2^53* (9007199254740992):

A solution is to use the MessageUtil.parseRequestID method like you do in the Unregister message
```
    public static Event parse(List<Object> wmsg) {
        MessageUtil.validateMessage(wmsg, MESSAGE_TYPE, "EVENT", 3, 6);
        long subscription = MessageUtil.parseRequestID(wmsg.get(1));
        long publication = MessageUtil.parseRequestID(wmsg.get(2));
```

Another  solution would be to configure Jackson to always deserialize numbers into longs (since Jackson 2.6)

```java
    public ISerializer(JsonFactory factor) {
        mapper = new ObjectMapper(factor);
        mapper.enable(DeserializationFeature.USE_LONG_FOR_INTS);
    }
```

But then you have the problem in the method Session.onMessage. The cast of the messageType no longer works because it is a Long

```java
    @Override
    public void onMessage(byte[] payload, boolean isBinary) throws Exception {
        // transform bytes to raw message:
        List<Object> rawMessage = mSerializer.unserialize(payload, isBinary);

        // transform raw message to typed message:
        try {
            int messageType = (int) rawMessage.get(0);
```

### PR DESCRIPTION
**Pull request by ralscha**
Resolves #363

### CODE REVIEW

**Comment by oberstet** [comment]
Cool, thanks! This looks good to me .. just wondering:

1. What `mapper.enable(DeserializationFeature.USE_LONG_FOR_INTS);` effects has on user code ..
2. WAMP request IDs must be long .. everywhere in the message classes .. just needs double checking

**Comment by ralscha** [comment]
USE_LONG_FOR_INTS changes everything in the response to long. Therefore this affects users code. 
Maybe this was not a good idea.

**Comment by oberstet** [comment]
> Maybe this was not a good idea.

yeah, sorry, I didn't thought about this as we discussed on #363 too. obviously, there would be a way to tell Jackson how to deserialize (and also serialize!) longs for WAMP IDs only .. is there?

**Comment by ralscha** [comment]
We can use MessageUtils.parseRequestID everywhere. I think this is the better solution and does not affect user code. 
Can you delete this pull request and I will create a new one

**Comment by om26er** [comment]
> Can you delete this pull request and I will create a new one

sure :)

**Pull request closed without merging**
