### PR TITLE
Fix TestClient

### PR DESCRIPTION
**Pull request by om26er**
Fix testclient to add interval between each run, it seems previously we were trying to reuse the same WebSocketConnection object, which is bad in so many ways(though that helped us discover a few leaks). To fix that, I am now creating a new WebSocketConnection object for each test, this is much stable than the previous approach. Though it seems Android chickens out due to lack of resources when we create too many threads. So the fix was to wait between each test so that the garbage collector does it job.

The bug that I discovered is that if our client receives a message frame after receiving a closeFrame, we are not ignoring that message and rather end up calling the onClose callback again, with "lost connection", I have fixed that partially but its not fully fixed as there are still cases that can cause that issue.

I have again bumped the minimum Android requirement because requesting a larger heapSize is a feature that is supported on API level 14+

### CODE REVIEW

**Comment by om26er** [comment]
Ok, we can now land this, The situation is better, though not 100% tests are passing, but we will get there.

There are a few pending bugs, especially the one where onClose can in some cases be called twice, but I will fix that in another pull request. Also attached the test results.

[test-report-result.zip](https://github.com/crossbario/autobahn-java/files/1007789/test-report-result.zip)

**Comment by om26er** [comment]
Attached latest report after tweaking some options (max message payload size), which were the cause of a few failures. The 4 failures are all due to the same reason that I mentioned in https://github.com/crossbario/autobahn-java/issues/125 

[reports.zip](https://github.com/crossbario/autobahn-java/files/1007975/reports.zip)

**Comment by om26er** [comment]
I believe the latest report might not be correct. The last that I produced locally, which I can't find right now had 4 failures. And all had the same cause: i.e. the test did not finish within 100 seconds due to the new implementation being slower.

**Comment by oberstet** [comment]
I got the apk built - awesome!! Thanks for the script, I basically pasted that into the Makefile, so it's just `make run`. So this is already nice. Will try the apk tomorrow and report back what I find.

**Comment by om26er** [comment]
Sounds, good.

I have now attached results of a latest run. Took 30 minutes to complete.
[report-4-failures.zip](https://github.com/crossbario/autobahn-java/files/1009067/report-4-failures.zip)

**Comment by om26er** [comment]
If we can land this one that'd be great. I have two branches that are based on this. One is a cleanup branch and the other fixes a handful of bugs both newly discovered(by me) and previously reported by others. Once we land those two and this one, I think that will help you better test the new code base.

**Pull request merged**
