### PR TITLE
break CI

### PR DESCRIPTION
**Pull request by om26er**
just testing

### CODE REVIEW

**Comment by oberstet** [comment]
This is the Python side .. what about the Java side? What if it compiles and runs, but produces a run-time exception? What if the call in the basic example returns with an (unexpected) WAMP level error (rather a Java syntax or run-time error)? So I want to make sure the CI raises red flags in all relevant cases (because I have fallen into this before) ;)

**Comment by om26er** [comment]
> This is the Python side .. what about the Java side? What if it compiles and runs, but produces a run-time exception? What if the call in the basic example returns with an (unexpected) WAMP level error (rather a Java syntax or run-time error)? So I want to make sure the CI raises red flags in all relevant cases (because I have fallen into this before) ;)

Looking into that. The `before_script` we currently have runs the docker containers in the background(-d), so a syntax error in the python file is ignored. Need to fix that somehow.

**Comment by oberstet** [comment]
Cool! This is good. Once we have a hashed out, robust CI for Docker based ABJ library and app development (because the "unit tests" are more integration tests, which are more like apps), we can also reuse that in the xbr app CI ..

**Comment by om26er** [comment]
So the problem is if a docker container is started with -d the exit code is 0, so travis thinks "all good".

**Comment by om26er** [comment]
Closing this now. The `before_script` part needs rethinking because we start our container as a daemon so the exit code is always 0.

For exiting on WAMP code failure, I have an other PR.

**Pull request closed without merging**
