### PR TITLE
Add publish/subscribe interaction to examples

### PR DESCRIPTION
**Pull request by om26er**

### CODE REVIEW

**Comment by oberstet** [comment]
Awesome! Heh, Travis fails because of: "The job exceeded the maximum time limit for jobs, and has been terminated." - which was to be expected, as this client does not exit.

So the follow up question would be if we wanted to split out actual CI integration tests to run from examples like the code now has been extended. Thoughts?

**Comment by oberstet** [comment]
publish/subscribe looks great! very nice.

so actually, it is only missing "register", and then it's complete!

**Comment by om26er** [comment]
So I think its stuck because we are not calling Session.leave() anywhere, so it keeps on running.

**Comment by om26er** [comment]
> another thing that appears to me is: we could make use of the ability to have more than one "on-join" observer, like demonstate each pattern in a different observer ..

That would only be about moving each interaction into a new method. Want me to do that now ?

**Comment by oberstet** [comment]
@om26er yes, pls!

also: make the outgoing calls also once per sec .. as close to the beh. as the py example .. docker works great btw for these kind of workflows! building/testing is a breeze ..

**Pull request merged**
