### PR TITLE
Make Session thread safe without adding any blocking operations. Fixe…

### PR DESCRIPTION
**Pull request by fhriley**
…s #329.

### CODE REVIEW

**Comment by om26er** [comment]
My main concern with the use of ConcurrentHashMap and ConcurrentLinkedQueue or even AtomicLong is that it limits us to support older version of android. Currently we have `enable_old_androids.sh` on the root of the project that replaces some of the imports with ones from the [streamsupport](https://github.com/streamsupport/streamsupport) backport project.

The above mentioned classes are not available in that project. We are also trying to keep the Session code use java8 exclusivity as little as possible. Check https://github.com/crossbario/autobahn-java/pull/285 which we merged recently just to achieve that.

To mention an undocumented fact: On Android, apart from network operations happening inside AndroidWebSocket class(uses threads), all user facing callbacks are executing on the main thread. Even though we are using async methods like runAsync() etc, the executor (CurrentThreadExecutor) that we use on that platform runs code on the main(UI) thread.

Now I do agree that running the user facing callbacks should probably run synchronous, though the architect of this library is @oberstet and it's very important to get his opinion on this one.

**Comment by fhriley** [comment]
Ah, I see. I'm not an Android guy nor a Java guy so I'm not familiar with all these issues. I don't think running callbacks synchronous is the solution. A message can arrive at any time so just making the callbacks synchronous will not solve the thread safety problem. Also, for the project I am working on, I am more concerned about latency so synchronous operations are bad. Unfortunately, without these concurrent data structures (short of writing your own, which I wouldn't recommend), we're left with synchronous operations (synchronized, etc). If it comes down to that I'll just fork the library to create a low latency version. There are already other things I need that aren't in the library anyway.

**Comment by om26er** [comment]
Hey @fhriley sorry for my previously misinformed comment. The APIs that talk above are actually available in Android by default. I'll do a few tests and will land this one later tonight.

**Comment by om26er** [comment]
Well, my tests were quick and they ran fine. Thanks for contributing.

**Pull request merged**
